/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMusicAdmin: typeof import('./src/components/addMusicAdmin.vue')['default']
    AddMusicListAdmin: typeof import('./src/components/AddMusicListAdmin.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Button: typeof import('./src/components/button.vue')['default']
    ButtonW: typeof import('./src/components/buttonW.vue')['default']
    Chaves: typeof import('./src/components/chaves.vue')['default']
    Footer: typeof import('./src/components/footerComplete.vue')['default']
    FooterComplete: typeof import('./src/components/footerComplete.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ListCantores: typeof import('./src/components/ListCantores.vue')['default']
    MusicList: typeof import('./src/components/MusicList.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    Pc: typeof import('./src/components/pc.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    Queue: typeof import('./src/components/Queue.vue')['default']
    QueueModal: typeof import('./src/components/QueueModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadTest: typeof import('./src/components/UploadTest.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
    UsersAdmin: typeof import('./src/components/usersAdmin.vue')['default']
  }
}
