/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/AllMusic': RouteRecordInfo<'/AllMusic', '/AllMusic', Record<never, never>, Record<never, never>>,
    '/Biblioteca': RouteRecordInfo<'/Biblioteca', '/Biblioteca', Record<never, never>, Record<never, never>>,
    '/Cantor': RouteRecordInfo<'/Cantor', '/Cantor', Record<never, never>, Record<never, never>>,
    '/Cantores': RouteRecordInfo<'/Cantores', '/Cantores', Record<never, never>, Record<never, never>>,
    '/Conta': RouteRecordInfo<'/Conta', '/Conta', Record<never, never>, Record<never, never>>,
    '/favoritos': RouteRecordInfo<'/favoritos', '/favoritos', Record<never, never>, Record<never, never>>,
    '/Genero': RouteRecordInfo<'/Genero', '/Genero', Record<never, never>, Record<never, never>>,
    '/Mes': RouteRecordInfo<'/Mes', '/Mes', Record<never, never>, Record<never, never>>,
    '/Pastas': RouteRecordInfo<'/Pastas', '/Pastas', Record<never, never>, Record<never, never>>,
    '/RegisterAndLogin': RouteRecordInfo<'/RegisterAndLogin', '/RegisterAndLogin', Record<never, never>, Record<never, never>>,
    '/Repertorios': RouteRecordInfo<'/Repertorios', '/Repertorios', Record<never, never>, Record<never, never>>,
    '/teste1212': RouteRecordInfo<'/teste1212', '/teste1212', Record<never, never>, Record<never, never>>,
    '/Tutoriais': RouteRecordInfo<'/Tutoriais', '/Tutoriais', Record<never, never>, Record<never, never>>,
  }
}
