import test,{before,after} from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing'
import {doc,setDoc,updateDoc,getDoc,collection,getDocs,query,where} from 'firebase/firestore'
let env
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-repertorio-rules',firestore:{host:'127.0.0.1',port:8080,rules:await readFile('firestore.rules','utf8')}});await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,'users','alice'),{email:'alice@test.com',role:'user',subscription:'inativa',firstName:'Alice',lastName:'A',favorites:[]});await setDoc(doc(db,'users','bob'),{role:'user',favorites:[]});await setDoc(doc(db,'users','admin'),{role:'admin',disabled:false});await setDoc(doc(db,'activationKeys','secret'),{days:30});await setDoc(doc(db,'downloads','one'),{uid:'bob'});await setDoc(doc(db,'playlists','bob-list'),{uid:'bob',name:'Bob',trackIds:[]})})})
after(async()=>env?.cleanup())
test('usuário não pode ler outra conta, chaves, downloads ou playlist',async()=>{const db=env.authenticatedContext('alice').firestore();for(const path of ['users/bob','activationKeys/secret','downloads/one','playlists/bob-list'])await assertFails(getDoc(doc(db,path)))})
test('usuário não pode criar ou alterar assinatura, papel ou senha',async()=>{const db=env.authenticatedContext('alice').firestore();await assertFails(updateDoc(doc(db,'users','alice'),{role:'admin'}));await assertFails(updateDoc(doc(db,'users','alice'),{subscription:'ativa',subscriptionEnd:'2099-01-01'}));await assertFails(updateDoc(doc(db,'users','alice'),{password:'plaintext'}));await assertFails(setDoc(doc(env.authenticatedContext('mallory',{email:'m@test.com'}).firestore(),'users','mallory'),{role:'admin',email:'m@test.com',subscription:'ativa',firstName:'M',lastName:'A',favorites:[]}))})
test('perfil e favoritos podem ser atualizados pelo dono',async()=>{const db=env.authenticatedContext('alice').firestore();await assertSucceeds(updateDoc(doc(db,'users','alice'),{firstName:'Nova Alice',favorites:['track']}))})
test('playlist exige dono e protege mudança de proprietário',async()=>{const db=env.authenticatedContext('alice').firestore();await assertSucceeds(setDoc(doc(db,'playlists','alice-list'),{uid:'alice',name:'Forró',trackIds:['track']}));await assertFails(updateDoc(doc(db,'playlists','alice-list'),{uid:'bob'}));await assertSucceeds(getDocs(query(collection(db,'playlists'),where('uid','==','alice'))))})
test('catálogo é público e gravações financeiras passam somente pela API',async()=>{await assertSucceeds(getDocs(collection(env.unauthenticatedContext().firestore(),'musicas')));await assertFails(setDoc(doc(env.authenticatedContext('admin').firestore(),'musicas','evil'),{title:'x'}));await assertFails(setDoc(doc(env.authenticatedContext('admin').firestore(),'activationKeys','new'),{days:30}));await assertSucceeds(getDoc(doc(env.authenticatedContext('admin').firestore(),'activationKeys','secret')))})
test('cadastro normal válido e sem senha é permitido',async()=>{const db=env.authenticatedContext('new-user',{email:'new@test.com'}).firestore();await assertSucceeds(setDoc(doc(db,'users','new-user'),{email:'new@test.com',role:'user',subscription:'inativa',firstName:'New',lastName:'User',favorites:[]}));assert.equal((await getDoc(doc(db,'users','new-user'))).data().role,'user')})
