import test from 'node:test'
import assert from 'node:assert/strict'
import {active,renewalEnd,uniqueIds,metadata,assertPublished} from '../server/policy.js'
import {nextTrack,filterTracks,normalizeTrack,dateOf} from '../src/utils/catalog.js'
import {parseCsv} from '../src/utils/csv.js'
import {encode,decode} from '../server/backup.js'
import {validSignature} from '../api/payment-webhook.js'
import {createHmac} from 'node:crypto'
const now=Date.parse('2026-10-02T00:00:00Z')
test('renovação preserva dias restantes e recomeça assinatura expirada',()=>{assert.equal(renewalEnd('2026-10-12T00:00:00Z',30,now),'2026-11-11T00:00:00.000Z');assert.equal(renewalEnd('2026-09-01T00:00:00Z',30,now),'2026-11-01T00:00:00.000Z');assert.throws(()=>renewalEnd(null,-1,now));assert.throws(()=>renewalEnd(null,1.5,now))})
test('assinatura considera validade, status e desativação',()=>{assert.equal(active({subscription:'ativa',subscriptionEnd:'2026-10-12'},now),true);assert.equal(active({subscription:'ativa',subscriptionEnd:'2026-09-01'},now),false);assert.equal(active({subscription:'ativa',subscriptionEnd:'2026-10-12',disabled:true},now),false);assert.equal(active({subscription:'inativa',subscriptionEnd:'2026-10-12'},now),false)})
test('seleção automática prioriza gênero e evita repetição recente',()=>{const current={id:'a',tipo:['Forró'],downloadUrl:'x'};const pool=[current,{id:'b',tipo:['Rock'],downloadUrl:'x'},{id:'c',estilos:['forro'],downloadUrl:'x'},{id:'d',tipo:['Forró'],downloadUrl:'x'}];assert.equal(nextTrack(current,pool,['c']).id,'d');assert.equal(nextTrack(current,pool.slice(0,2)).id,'b');assert.equal(nextTrack(current,[current]),null)})
test('rascunhos, indisponíveis e agendados não entram na seleção',()=>{const current={id:'a',tipo:['Forró']};const future={id:'b',tipo:['Forró'],downloadUrl:'x',publishAt:'2099-01-01'};assert.equal(nextTrack(current,[future]),null);assert.throws(()=>assertPublished(future));assert.throws(()=>assertPublished({status:'draft'}));assert.throws(()=>assertPublished({disabled:true}))})
test('busca combina cantor, gênero, mês e acentos',()=>{const tracks=[normalizeTrack({id:'a',title:'Coração',cantor:'José',tipo:['Forró'],createdAt:'2026-10-02'}),normalizeTrack({id:'b',title:'Outra',cantor:'Ana',tipo:['Rock'],createdAt:'2026-09-02'})];assert.deepEqual(filterTracks(tracks,{search:'coracao',artist:'José',genre:'Forró',month:'2026-10'}).map(t=>t.id),['a']);assert.equal(filterTracks(tracks,{search:'jose',month:'2026-09'}).length,0)})
test('IDs e metadados inválidos são rejeitados',()=>{assert.deepEqual(uniqueIds(['b','a','a']),['a','b']);assert.throws(()=>uniqueIds(['../secret']));assert.throws(()=>uniqueIds([]));assert.throws(()=>metadata({title:'a'}));assert.throws(()=>metadata({title:'a',cantor:'b',tipo:['c'],publishAt:'invalid'}));assert.equal(metadata({title:' a ',cantor:' b ',tipo:'Forró, Rock'}).tipo.length,2)})
test('CSV respeita aspas, delimitadores, BOM e limite',()=>{const rows=parseCsv('\uFEFFid;title;cantor;tipo\r\na;"Canção; especial";José;Forró\r\nb;"Diz ""oi""";Ana;Rock');assert.equal(rows[0].title,'Canção; especial');assert.equal(rows[1].title,'Diz "oi"');assert.throws(()=>parseCsv('title,cantor\nx,y'));assert.throws(()=>parseCsv('id,title\na,"errado'))})
test('backup remove senhas e preserva timestamp',()=>{class Timestamp{constructor(seconds,nanoseconds){this.seconds=seconds;this.nanoseconds=nanoseconds}toDate(){return new Date(this.seconds*1000)}}const source={password:'secret',nested:{password:'secret'},at:new Timestamp(100,5)};const encoded=encode(source);assert.equal('password' in encoded,false);assert.equal('password' in encoded.nested,false);assert.equal(decode(encoded,Timestamp).at.seconds,100)})
test('webhook rejeita falsificação e notificações antigas',()=>{const secret='test',ts=String(Math.floor(now/1000)),request='abc',id='123';const signature=createHmac('sha256',secret).update(`id:${id};request-id:${request};ts:${ts};`).digest('hex');const headers={'x-request-id':request,'x-signature':`ts=${ts},v1=${signature}`};assert.equal(validSignature(headers,id,secret,now),true);assert.equal(validSignature(headers,id,'wrong',now),false);assert.equal(validSignature(headers,id,secret,now+700000),false);assert.equal(validSignature({},id,secret,now),false)})

test('datas serializadas pela API administrativa são normalizadas',()=>{assert.equal(dateOf({_seconds:100}).getTime(),100000);assert.equal(dateOf({seconds:100}).getTime(),100000);assert.equal(normalizeTrack({title:'Sem data',createdAt:'inválida'}).month,'1970-01')})
test('fila sem músicas reproduzíveis não entra em repetição infinita',()=>{assert.equal(nextTrack({id:'a',tipo:['Rock']},[{id:'a',downloadUrl:'x'},{id:'b',tipo:['Rock']}]),null)})
