<template><section class="page-shell"><header class="page-heading"><div><p class="eyebrow">GESTÃO DO REPERTÓRIO</p><h1>Administração</h1><p class="muted">Envios, catálogo, contas e histórico de operações.</p></div><button class="secondary" @click="refresh" :disabled="busy">Atualizar painel</button></header><div v-if="configuration" class="notice"><strong>Configuração dos serviços</strong><p>Firebase: conectado · R2: {{configuration.r2?'configurado':'pendente'}} · B2 S3: {{configuration.b2?'configurado':'pendente'}} · Pagamento: {{configuration.payments?'configurado':'pendente'}} · Preparação de pacotes: {{configuration.worker?'configurada':'pendente'}}</p></div><p role="status" class="status-message">{{message}}</p><nav class="admin-tabs" aria-label="Seções administrativas"><button v-for="t in tabs" :key="t.id" class="secondary" :class="{active:tab===t.id}" @click="tab=t.id">{{t.name}}</button></nav>
 <template v-if="tab==='upload'"><section class="panel"><h2>Enviar músicas</h2><p class="muted">Envio direto do celular ou computador. Os arquivos concluídos não serão reenviados ao tentar novamente.</p><div class="filter-bar"><label>Cantor<input v-model="artist" list="admin-artists" required><datalist id="admin-artists"><option v-for="a in artists" :key="a">{{a}}</option></datalist></label><label>Gêneros (separados por vírgula)<input v-model="genre" list="admin-genres" required><datalist id="admin-genres"><option v-for="g in genresList" :key="g">{{g}}</option></datalist></label><label>Publicar em<input v-model="publishAt" type="datetime-local"></label><label>Arquivos de áudio<input type="file" accept="audio/*,.mp3,.m4a,.wav,.ogg,.flac" multiple @change="selectFiles"></label></div><div v-for="(f,index) in files" :key="index" class="upload-row"><div><strong>{{f.file.name}}</strong><small>{{bytes(f.file.size)}}</small><progress :value="f.progress" max="100" :aria-label="`Progresso de ${f.file.name}`"></progress><p :class="f.error?'error':'success'">{{f.error || f.status}}</p></div><label>Título<input v-model="f.title" :disabled="f.done || busy"></label><button class="secondary" @click="sendOne(f)" :disabled="f.done || busy || !artist || !genre">{{f.error?'Tentar novamente':'Enviar'}}</button></div><div class="actions"><button class="primary" @click="sendAll" :disabled="busy || !files.length || !artist || !genre">{{busy?'Enviando…':'Enviar pendentes / tentar novamente'}}</button><button class="secondary" @click="files=files.filter(f=>!f.done)" :disabled="busy">Remover concluídos</button></div></section></template>
 <template v-if="tab==='catalog'"><section class="panel"><h2>Edição em lote e agendamento</h2><div class="filter-bar"><label>Buscar<input v-model="search" type="search"></label><label>Novo cantor<input v-model="editArtist"></label><label>Novos gêneros<input v-model="editGenre" placeholder="Separe por vírgulas"></label><label>Publicar em<input v-model="editDate" type="datetime-local"></label></div><div class="actions"><button class="primary" @click="editBatch" :disabled="busy || !selected.length">Salvar {{selected.length}} selecionadas</button><button class="secondary" @click="availability" :disabled="busy || !selected.length">Verificar arquivos</button><button class="secondary" @click="setDraft" :disabled="busy || !selected.length">Mover para rascunho</button><button class="secondary" @click="setPublished" :disabled="busy || !selected.length">Publicar agora</button></div><label>Importar informações por CSV<input type="file" accept=".csv" @change="importCsv"></label><p class="muted">CSV: id,title,cantor,tipo,publishAt. O ID precisa corresponder a uma música existente; nenhum arquivo é apagado. Até 200 linhas por importação.</p><a class="secondary" href="/modelo-musicas.csv" download>Baixar modelo CSV</a><p v-if="importRows.length">{{importRows.length}} linhas prontas para revisão</p><div v-if="importRows.length" class="table-wrap"><table><thead><tr><th>ID</th><th>Título</th><th>Cantor</th><th>Gêneros</th></tr></thead><tbody><tr v-for="r in importRows.slice(0,20)" :key="r.id"><td>{{r.id}}</td><td>{{r.title}}</td><td>{{r.cantor}}</td><td>{{r.tipo}}</td></tr></tbody></table><button class="primary" @click="commitImport" :disabled="busy">Confirmar importação</button></div><p role="status">{{catalog.error}}</p><label class="check"><input type="checkbox" :checked="visible.length>0 && visible.every(t=>selected.includes(t.id))" @change="selected=$event.target.checked?visible.map(t=>t.id):[]"> Selecionar resultados (até 200)</label><article class="queue-row" v-for="t in visible" :key="t.id"><label class="check"><input v-model="selected" type="checkbox" :value="t.id"><span><strong>{{t.title}}</strong><small>{{t.cantor}} · {{genres(t).join(', ')}} · {{t.status==='draft'?'Rascunho':t.publishAt?`Agendada: ${dateOf(t.publishAt).toLocaleString('pt-BR')}`:'Publicada'}}</small><small>ID: {{t.id}} · {{bytes(t.size)}} · {{availabilityResult[t.id]===undefined?'Arquivo ainda não verificado':availabilityResult[t.id]?'Disponível':'Indisponível'}}</small></span></label><button class="secondary" @click="editTrack=t;singleTitle=t.title">Editar título</button></article></section></template>
 <template v-if="tab==='users'"><section class="panel"><h2>Usuários e assinaturas</h2><button class="secondary" @click="exportUsers">Exportar usuários para Excel</button><label>Buscar conta<input v-model="userSearch" type="search"></label><article class="queue-row" v-for="u in filteredUsers" :key="u.id"><div><strong>{{u.firstName}} {{u.lastName}}</strong><small>{{u.email}} · {{u.role || 'user'}} · {{u.disabled?'Desativada':'Habilitada'}}</small><small>Validade: {{u.subscriptionEnd?dateOf(u.subscriptionEnd).toLocaleDateString('pt-BR'):'Sem assinatura'}}</small></div><div class="actions"><button class="secondary" @click="renewUser=u.id;renewDays=30">Renovar</button><button class="secondary" @click="toggleUser(u)" :disabled="busy || u.id===user.user?.uid">{{u.disabled?'Habilitar':'Desativar'}}</button></div></article></section></template>
 <template v-if="tab==='keys'"><section class="panel"><h2>Chaves de uso único</h2><form class="actions" @submit.prevent="createKey"><label>Duração em dias<input v-model.number="keyDays" type="number" min="1" max="3660" required></label><button class="primary" :disabled="busy">Gerar chave segura</button></form><p v-if="generatedKey" class="notice">Copie agora: <strong>{{generatedKey}}</strong><br>A chave completa só é exibida neste momento.</p><article class="queue-row" v-for="k in keys" :key="k.id"><div><strong>{{k.days}} dias · {{k.usedBy?'Utilizada':k.revoked?'Revogada':'Disponível'}}</strong><small>Identificador: {{k.id.slice(0,16)}}…</small></div><button v-if="!k.usedBy && !k.revoked" class="secondary" @click="revoke(k.id)">Revogar</button></article></section></template>
 <template v-if="tab==='dashboard'"><div class="stat-grid"><div class="panel"><small>Contas</small><strong>{{dashboard.summary?.users || 0}}</strong></div><div class="panel"><small>Assinaturas ativas</small><strong>{{dashboard.summary?.active || 0}}</strong></div><div class="panel"><small>Downloads solicitados</small><strong>{{dashboard.summary?.downloads || 0}}</strong></div><div class="panel"><small>Volume solicitado</small><strong style="font-size:22px">{{bytes(dashboard.summary?.requestedBytes)}}</strong></div></div><p class="muted">{{dashboard.summary?.accesses || 0}} autorizações de reprodução. Volume solicitado é uma estimativa, não a fatura do armazenamento. {{dashboard.summary?.limited?'Amostra limitada a 1.000 registros por coleção.':''}}</p><section class="panel"><h2>Pacotes</h2><article v-for="p in dashboard.packages || []" :key="p.id" class="queue-row"><div>{{p.ids?.length || 0}} músicas · {{bytes(p.size)}}<small>{{p.status}} · {{p.id.slice(0,12)}}</small></div></article></section><section class="panel"><h2>Publicar aviso</h2><form @submit.prevent="notify"><label>Mensagem<textarea v-model="notification" maxlength="500" required class="text-area"></textarea></label><button class="primary" :disabled="busy">Publicar no site</button></form></section><section class="panel"><h2>Histórico administrativo</h2><article v-for="a in auditRows" :key="a.id" class="queue-row"><div><strong>{{a.action}}</strong><small>{{a.actor}} · {{dateOf(a.at).toLocaleString('pt-BR')}}</small><details><summary>Detalhes</summary><pre>{{JSON.stringify(a.details,null,2)}}</pre></details></div></article></section></template>
 <template v-if="tab==='backup'"><section class="panel"><h2>Backup e recuperação</h2><p>Exporte o banco para o armazenamento privado. A recuperação começa por uma prévia das diferenças e exige confirmação antes de escrever.</p><div class="actions"><button class="primary" @click="backup" :disabled="busy">Criar backup privado</button><button class="secondary" @click="loadBackups" :disabled="busy">Atualizar lista</button></div><article v-for="b in backups" :key="b.id" class="queue-row"><div>{{dateOf(b.at).toLocaleString('pt-BR')}}<small>{{b.count}} documentos · {{b.id}}</small></div><button class="secondary" @click="previewRestore(b.id)">Prévia de recuperação</button></article><div v-if="restorePreview" class="notice"><strong>Prévia: {{restorePreview.count}} documentos</strong><p>Documentos existentes serão atualizados. Documentos extras atuais serão preservados. O backup não inclui senhas nem cópias dos áudios.</p><button class="secondary" @click="restorePreview=null">Cancelar</button><button class="primary" @click="restore" :disabled="busy">Confirmar recuperação</button></div></section></template>
 <v-dialog :model-value="!!editTrack" @update:model-value="v=>{if(!v)editTrack=null}" max-width="440"><v-card><v-card-title>Editar título</v-card-title><v-card-text><label>Título<input v-model="singleTitle" maxlength="200"></label></v-card-text><v-card-actions><v-btn @click="editTrack=null">Cancelar</v-btn><v-btn @click="saveTitle" :disabled="busy">Salvar</v-btn></v-card-actions></v-card></v-dialog>
 <v-dialog :model-value="!!renewUser" @update:model-value="v=>{if(!v)renewUser=null}" max-width="440"><v-card><v-card-title>Renovar assinatura</v-card-title><v-card-text><label>Dias a adicionar<input v-model.number="renewDays" type="number" min="1" max="3660"></label><p>Os dias restantes serão preservados.</p></v-card-text><v-card-actions><v-btn @click="renewUser=null">Cancelar</v-btn><v-btn @click="renew" :disabled="busy">Confirmar renovação</v-btn></v-card-actions></v-card></v-dialog>
 </section></template>
<script setup>
import {ref,computed,onMounted} from 'vue'
import {api} from '@/services/api'
import {uploadAudio,audioDuration} from '@/services/upload'
import {useCatalogStore} from '@/stores/catalogStore'
import {useUserStore} from '@/stores/userStore'
import {bytes,genres,dateOf,normalize} from '@/utils/catalog'
import {parseCsv} from '@/utils/csv'
const catalog=useCatalogStore(),user=useUserStore(),tab=ref('upload'),message=ref(''),busy=ref(false),configuration=ref(null),files=ref([]),artist=ref(''),genre=ref(''),publishAt=ref(''),search=ref(''),selected=ref([]),editArtist=ref(''),editGenre=ref(''),editDate=ref(''),editTrack=ref(null),singleTitle=ref(''),userSearch=ref(''),renewUser=ref(null),renewDays=ref(30),keyDays=ref(30),generatedKey=ref(''),keys=ref([]),dashboard=ref({}),importRows=ref([]),availabilityResult=ref({}),notification=ref(''),backups=ref([]),restorePreview=ref(null)
const tabs=[{id:'upload',name:'Enviar músicas'},{id:'catalog',name:'Catálogo'},{id:'users',name:'Usuários'},{id:'keys',name:'Chaves'},{id:'dashboard',name:'Painel e histórico'},{id:'backup',name:'Backup'}]
const artists=computed(()=>[...new Set(catalog.tracks.map(t=>t.cantor))].filter(Boolean).sort()),genresList=computed(()=>[...new Set(catalog.tracks.flatMap(genres))].sort()),visible=computed(()=>catalog.tracks.filter(t=>normalize(`${t.title} ${t.cantor}`).includes(normalize(search.value))).slice(0,200)),filteredUsers=computed(()=>(dashboard.value.users || []).filter(u=>normalize(`${u.firstName} ${u.lastName} ${u.email}`).includes(normalize(userSearch.value)))),auditRows=computed(()=>(dashboard.value.audit || []).sort((a,b)=>dateOf(b.at)-dateOf(a.at)))
async function run(fn){if(busy.value)return;busy.value=true;message.value='';try{await fn()}catch(e){message.value=e.message}finally{busy.value=false}}
async function refresh(){await run(async()=>{configuration.value=await api('configuration');dashboard.value=await api('dashboard');keys.value=(await api('keys-list')).keys;await catalog.load(true)})}
function selectFiles(event){for(const file of event.target.files)files.value.push({file,title:file.name.replace(/\.[^.]+$/,''),progress:0,status:'Aguardando',error:'',done:false});event.target.value=''}
async function upload(f){if(f.done)return;f.error='';f.status='Verificando arquivo…';try{const duration=await audioDuration(f.file);await uploadAudio(f.file,{title:f.title,cantor:artist.value,tipo:genre.value.split(',').map(s=>s.trim()).filter(Boolean),publishAt:publishAt.value?new Date(publishAt.value).toISOString():null,duration},progress=>{f.progress=progress;f.status=`Enviando ${progress}%`});f.done=true;f.status='Concluído'}catch(e){f.error=e.message;f.status='Falhou'}}
async function sendOne(f){await run(async()=>{await upload(f);await catalog.load(true)})}
async function sendAll(){await run(async()=>{for(const f of files.value.filter(f=>!f.done))await upload(f);await catalog.load(true);message.value=`${files.value.filter(f=>f.done).length} concluídos; ${files.value.filter(f=>f.error).length} falharam.`})}
function editBatch(){run(async()=>{const changes={};if(editArtist.value)changes.cantor=editArtist.value;if(editGenre.value)changes.tipo=editGenre.value.split(',').map(s=>s.trim()).filter(Boolean);if(editDate.value)changes.publishAt=new Date(editDate.value).toISOString();const r=await api('music-edit',{ids:selected.value,changes});message.value=`${r.updated} músicas atualizadas.`;await catalog.load(true)})}
function setDraft(){run(async()=>{await api('music-edit',{ids:selected.value,changes:{status:'draft'}});await catalog.load(true);message.value='Músicas movidas para rascunho.'})}
function setPublished(){run(async()=>{await api('music-edit',{ids:selected.value,changes:{status:'published',publishAt:null}});await catalog.load(true);message.value='Músicas publicadas.'})}
function saveTitle(){run(async()=>{await api('music-edit',{ids:[editTrack.value.id],changes:{title:singleTitle.value}});editTrack.value=null;await catalog.load(true)})}
function availability(){run(async()=>{const r=await api('music-check',{ids:selected.value.slice(0,10)});availabilityResult.value={...availabilityResult.value,...Object.fromEntries(r.results.map(v=>[v.id,v.available]))};message.value='Verificadas até 10 músicas por solicitação.'})}
async function importCsv(event){try{importRows.value=parseCsv(await event.target.files[0].text());message.value=`Revise ${importRows.value.length} linhas antes de confirmar.`}catch(e){message.value=e.message}event.target.value=''}
function commitImport(){run(async()=>{const r=await api('music-import',{rows:importRows.value});message.value=`${r.updated} músicas atualizadas.`;importRows.value=[];await catalog.load(true)})}
async function exportUsers(){const XLSX=await import('xlsx');const rows=(dashboard.value.users || []).map(u=>({Nome:[u.firstName,u.lastName].filter(Boolean).join(' '),Email:u.email,Telefone:u.numero || '',Papel:u.role || 'user',Assinatura:u.subscription || 'inativa',Validade:u.subscriptionEnd?dateOf(u.subscriptionEnd).toLocaleDateString('pt-BR'):'',Desativada:u.disabled?'Sim':'Não'}));const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(rows),'Usuários');XLSX.writeFile(workbook,'usuarios-repertorio.xlsx')}
function toggleUser(u){run(async()=>{await api('user-edit',{uid:u.id,disabled:!u.disabled});dashboard.value=await api('dashboard')})}
function renew(){run(async()=>{await api('user-edit',{uid:renewUser.value,days:renewDays.value});renewUser.value=null;dashboard.value=await api('dashboard');message.value='Assinatura renovada.'})}
function createKey(){run(async()=>{generatedKey.value=(await api('keys-create',{days:keyDays.value})).key;keys.value=(await api('keys-list')).keys;dashboard.value=await api('dashboard')})}
function revoke(id){run(async()=>{await api('keys-revoke',{id});keys.value=(await api('keys-list')).keys})}
function notify(){run(async()=>{await api('notify',{message:notification.value});notification.value='';message.value='Aviso publicado.'})}
function backup(){run(async()=>{await api('backup-create');backups.value=(await api('backup-list')).backups;message.value='Backup privado criado.'})}
function loadBackups(){run(async()=>backups.value=(await api('backup-list')).backups)}
function previewRestore(id){run(async()=>restorePreview.value=await api('backup-preview',{id}))}
function restore(){run(async()=>{await api('backup-restore',{id:restorePreview.value.id,token:restorePreview.value.token});restorePreview.value=null;message.value='Dados recuperados.';await catalog.load(true)})}
onMounted(refresh)
</script>
