<template><section class="page-shell"><header class="page-heading"><div><p class="eyebrow">ORGANIZE SEU SOM</p><h1>Minha biblioteca</h1><p class="muted">Playlists pessoais e favoritos salvos na sua conta.</p></div></header><p v-if="!user.user">Entre na sua conta para criar playlists. <router-link to="/RegisterAndLogin?mode=login">Entrar</router-link></p><template v-else><form class="actions" @submit.prevent="create"><label>Nova playlist<input v-model="name" maxlength="80" required placeholder="Nome da playlist"></label><button class="primary" :disabled="busy">Criar playlist</button></form><p role="status">{{message}}</p><div class="discovery-grid"><button class="discovery-card" @click="active=null"><i class="mdi mdi-heart"></i><strong>Favoritos</strong><small>{{user.user.favorites?.length || 0}} músicas</small></button><button class="discovery-card" v-for="p in playlists" :key="p.id" @click="active=p.id"><i class="mdi mdi-playlist-music"></i><strong>{{p.name}}</strong><small>{{p.trackIds?.length || 0}} músicas</small></button></div><template v-if="selectedPlaylist"><h2>{{selectedPlaylist.name}}</h2><form class="actions" @submit.prevent="rename"><label>Renomear<input v-model="renameValue" maxlength="80" required></label><button class="secondary">Salvar nome</button><button class="secondary" type="button" @click="deleteDialog=true">Excluir playlist</button><button class="primary" type="button" @click="playAll">Reproduzir playlist</button></form><article class="queue-row" v-for="t in playlistTracks" :key="t.id"><button @click="play(t)">{{t.title}} · {{t.cantor}}</button><button class="icon-button" @click="remove(t.id)" :aria-label="`Remover ${t.title} da playlist`"><i class="mdi mdi-close"></i></button></article><p v-if="!playlistTracks.length">Adicione músicas pelo botão de playlist no catálogo.</p></template><MusicExplorer v-else heading="Meus favoritos" :favorites="true"/></template><v-dialog v-model="deleteDialog" max-width="420"><v-card><v-card-title>Excluir {{selectedPlaylist?.name}}?</v-card-title><v-card-text>As músicas continuarão no catálogo.</v-card-text><v-card-actions><v-btn @click="deleteDialog=false">Cancelar</v-btn><v-btn @click="deletePlaylist">Excluir</v-btn></v-card-actions></v-card></v-dialog></section></template>
<script setup>
import {ref,computed,watch,onBeforeUnmount} from 'vue'
import {collection,query,where,onSnapshot,addDoc,doc,updateDoc,deleteDoc,arrayRemove,serverTimestamp} from 'firebase/firestore'
import {db} from '@/firebase'
import {useUserStore} from '@/stores/userStore'
import {useCatalogStore} from '@/stores/catalogStore'
import {usePlayerStore} from '@/stores/usePlayerStore'
import MusicExplorer from '@/components/MusicExplorer.vue'
const user=useUserStore(),catalog=useCatalogStore(),player=usePlayerStore(),name=ref(''),renameValue=ref(''),playlists=ref([]),active=ref(null),busy=ref(false),message=ref(''),deleteDialog=ref(false);let unsubscribe
const selectedPlaylist=computed(()=>playlists.value.find(p=>p.id===active.value)),playlistTracks=computed(()=>(selectedPlaylist.value?.trackIds || []).map(id=>catalog.tracks.find(t=>t.id===id)).filter(Boolean))
watch(()=>user.user?.uid,uid=>{unsubscribe?.();playlists.value=[];if(uid)unsubscribe=onSnapshot(query(collection(db,'playlists'),where('uid','==',uid)),s=>playlists.value=s.docs.map(d=>({...d.data(),id:d.id})),()=>message.value='Não foi possível carregar as playlists.')},{immediate:true})
watch(selectedPlaylist,p=>renameValue.value=p?.name || '')
async function create(){busy.value=true;try{const p=await addDoc(collection(db,'playlists'),{uid:user.user.uid,name:name.value.trim(),trackIds:[],createdAt:serverTimestamp()});name.value='';active.value=p.id}catch{message.value='Não foi possível criar a playlist.'}finally{busy.value=false}}
async function rename(){try{await updateDoc(doc(db,'playlists',active.value),{name:renameValue.value.trim()})}catch{message.value='Não foi possível renomear.'}}
async function remove(id){try{await updateDoc(doc(db,'playlists',active.value),{trackIds:arrayRemove(id)})}catch{message.value='Não foi possível remover.'}}
async function deletePlaylist(){try{await deleteDoc(doc(db,'playlists',active.value));active.value=null;deleteDialog.value=false}catch{message.value='Não foi possível excluir.'}}
function play(t){if(!user.hasActiveSubscription){message.value='Ative a assinatura para ouvir.';return}player.addToQueue(t,{playNow:true})}
function playAll(){if(!user.hasActiveSubscription){message.value='Ative a assinatura para ouvir.';return}player.clearQueue();player.queue=[...playlistTracks.value];player.play(0)}
catalog.load();onBeforeUnmount(()=>unsubscribe?.())
</script>
