<template><section class="auth-shell"><form class="panel" @submit.prevent="submit"><p class="eyebrow">REPERTÓRIO ATUALIZADO</p><h1>{{mode==='reset'?'Recuperar senha':mode==='register'?'Criar conta':'Entrar'}}</h1><template v-if="mode==='register'"><label>Nome<input v-model="firstName" required maxlength="80" autocomplete="given-name"></label><label>Sobrenome<input v-model="lastName" required maxlength="100" autocomplete="family-name"></label><label>Telefone<input v-model="numero" type="tel" maxlength="25" autocomplete="tel"></label></template><label>E-mail<input v-model="email" required type="email" autocomplete="email" maxlength="254"></label><template v-if="mode!=='reset'"><label>Senha<input v-model="password" required :minlength="mode==='register'?8:6" type="password" :autocomplete="mode==='register'?'new-password':'current-password'"></label><label v-if="mode==='register'">Confirmar senha<input v-model="confirmation" required minlength="8" type="password" autocomplete="new-password"></label></template><p v-if="message" role="status">{{message}}</p><button class="primary" :disabled="busy">{{busy?'Aguarde…':mode==='reset'?'Enviar recuperação':mode==='register'?'Criar conta':'Entrar'}}</button><div class="actions"><router-link v-if="mode!=='login'" to="/RegisterAndLogin?mode=login">Já tenho conta</router-link><router-link v-if="mode!=='register'" to="/RegisterAndLogin?mode=register">Criar conta</router-link><router-link v-if="mode!=='reset'" to="/RegisterAndLogin?mode=reset">Esqueci minha senha</router-link></div></form></section></template>
<script setup>
import {ref,computed} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,updateProfile,signOut} from 'firebase/auth'
import {doc,setDoc,getDoc,serverTimestamp} from 'firebase/firestore'
import {auth,db} from '@/firebase'
const route=useRoute(),router=useRouter(),mode=computed(()=>['register','reset'].includes(route.query.mode)?route.query.mode:'login'),email=ref(''),password=ref(''),confirmation=ref(''),firstName=ref(''),lastName=ref(''),numero=ref(''),busy=ref(false),message=ref('')
async function submit(){busy.value=true;message.value='';try{const normalizedEmail=email.value.trim().toLowerCase();if(mode.value==='reset'){await sendPasswordResetEmail(auth,normalizedEmail);message.value='Se houver uma conta com esse e-mail, você receberá as instruções.';return}if(mode.value==='register'){if(password.value!==confirmation.value)throw Error('As senhas não coincidem.');const result=await createUserWithEmailAndPassword(auth,normalizedEmail,password.value);await updateProfile(result.user,{displayName:firstName.value.trim()});await setDoc(doc(db,'users',result.user.uid),{firstName:firstName.value.trim(),lastName:lastName.value.trim(),numero:numero.value.trim(),email:normalizedEmail,role:'user',subscription:'inativa',favorites:[],createdAt:serverTimestamp()})}else{const result=await signInWithEmailAndPassword(auth,normalizedEmail,password.value);const snap=await getDoc(doc(db,'users',result.user.uid));if(snap.data()?.disabled){await signOut(auth);throw Error('Conta desativada. Entre em contato com o suporte.')}}password.value='';confirmation.value='';router.push('/Conta')}catch(e){message.value=({'auth/email-already-in-use':'Este e-mail já está cadastrado.','auth/invalid-credential':'E-mail ou senha incorretos.','auth/too-many-requests':'Muitas tentativas. Aguarde e tente novamente.','auth/weak-password':'Use uma senha mais forte.','auth/network-request-failed':'Verifique sua conexão.'})[e.code] || (e.code?'Não foi possível concluir. Tente novamente.':e.message)}finally{busy.value=false}}
</script>
