import {createHash} from 'node:crypto'
import {Readable,Transform} from 'node:stream'
import {Upload} from '@aws-sdk/lib-storage'
import {HeadObjectCommand,GetObjectCommand} from '@aws-sdk/client-s3'
import {database,storage,signMedia,timestamp,FieldValue} from '../api/_lib/admin.js'
const db=database(),apply=process.argv.includes('--apply'),snapshot=await db.collection('musicas').get(),songs=snapshot.docs.filter(s=>!s.data().storageKey && s.data().downloadUrl)
console.log(`${songs.length} músicas legadas disponíveis para migração. B2 não será apagado.`)
if(!apply){console.log('Prévia somente. Crie um backup antes de executar --apply.');process.exit(0)}
const {client,Bucket}=storage('r2')
for(const s of songs){try{const track=s.data(),url=await signMedia(track),response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(120000)});if(!response.ok || !response.body)throw Error('Origem indisponível');let size=0;const digest=createHash('sha256'),counter=new Transform({transform(chunk,encoding,cb){size+=chunk.length;digest.update(chunk);cb(null,chunk)}});const key=`audio/${s.id}/${(track.fileName || `${s.id}.mp3`).replace(/[^\p{L}\p{N}._ -]/gu,'_')}`;await new Upload({client,params:{Bucket,Key:key,Body:Readable.fromWeb(response.body).pipe(counter),ContentType:response.headers.get('content-type') || 'audio/mpeg'}}).done();const sha256=digest.digest('hex');const head=await client.send(new HeadObjectCommand({Bucket,Key:key}));if(head.ContentLength!==size)throw Error('Tamanho divergente');const copied=await client.send(new GetObjectCommand({Bucket,Key:key}));const copiedHash=createHash('sha256');for await(const chunk of copied.Body)copiedHash.update(chunk);if(copiedHash.digest('hex')!==sha256)throw Error('Checksum divergente');const batch=db.batch();batch.set(db.collection('migrations').doc(s.id),{legacyUrl:track.downloadUrl,storageKey:key,sha256,size,at:timestamp()});batch.update(s.ref,{storageKey:key,storageProvider:'r2',size,sha256,downloadUrl:FieldValue.delete(),migratedAt:timestamp()});batch.set(db.collection('fileHashes').doc(sha256),{musicId:s.id});await batch.commit();console.log('Migrada:',s.id)}catch(e){console.error('Falha:',s.id,e.name)}}
